//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Vmstats.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IVmstatsListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class VmstatsBaseListener : IVmstatsListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VmstatsParser.transform_pipeline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransform_pipeline([NotNull] VmstatsParser.Transform_pipelineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VmstatsParser.transform_pipeline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransform_pipeline([NotNull] VmstatsParser.Transform_pipelineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VmstatsParser.transform"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransform([NotNull] VmstatsParser.TransformContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VmstatsParser.transform"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransform([NotNull] VmstatsParser.TransformContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VmstatsParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] VmstatsParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VmstatsParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] VmstatsParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VmstatsParser.combine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCombine([NotNull] VmstatsParser.CombineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VmstatsParser.combine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCombine([NotNull] VmstatsParser.CombineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VmstatsParser.metric_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetric_name([NotNull] VmstatsParser.Metric_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VmstatsParser.metric_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetric_name([NotNull] VmstatsParser.Metric_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VmstatsParser.transform_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransform_name([NotNull] VmstatsParser.Transform_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VmstatsParser.transform_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransform_name([NotNull] VmstatsParser.Transform_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VmstatsParser.parameter_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_name([NotNull] VmstatsParser.Parameter_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VmstatsParser.parameter_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_name([NotNull] VmstatsParser.Parameter_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VmstatsParser.value_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue_name([NotNull] VmstatsParser.Value_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VmstatsParser.value_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue_name([NotNull] VmstatsParser.Value_nameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
