//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Vmstats.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="VmstatsParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IVmstatsVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="VmstatsParser.transform_pipeline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransform_pipeline([NotNull] VmstatsParser.Transform_pipelineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VmstatsParser.transform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransform([NotNull] VmstatsParser.TransformContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VmstatsParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] VmstatsParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VmstatsParser.combine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCombine([NotNull] VmstatsParser.CombineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VmstatsParser.metric_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMetric_name([NotNull] VmstatsParser.Metric_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VmstatsParser.transform_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransform_name([NotNull] VmstatsParser.Transform_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VmstatsParser.parameter_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_name([NotNull] VmstatsParser.Parameter_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VmstatsParser.value_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_name([NotNull] VmstatsParser.Value_nameContext context);
}
