version: '3'

services:
  vmstats:
    image: joncatlin/vmstats
    volumes:
      - "/mount/general-data/vmstats-data/:/data"
      - "/mount/general-data/vmstats-config/:/config"
      - "/mount/general-data/vmstats-snapshots/:/snapshots"
    restart: always
    environment:
      VMNAME_PATTERN: "V-BWill.*"
    ports:
      - "8080:80"
