version: '3'
services:

  vmstats:
    image: joncatlin/csl-vmstats-akka
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/mount/vmstats-data/Desktops/:/data"
      - "/mount/vmstats-processed-data/vmstats-config/:/config"
      - "/mount/vmstats-processed-data/vmstats-snapshots/:/snapshots"
      - "/mount/vmstats-processed-data/vmstats-logs/:/logs"
    environment:
      VMNAME_PATTERN: "V-.*"
      VMSTATSGUI_WEBSERVER_URL: "http://docker01.dest.internal:8081/vmstats/ReturnResultToClient"
      DIR_NAME: "/data"
      FILE_TYPE: "*.csv"
      CONFIG_FILE: "/config/config.txt"
      SNAPSHOT_PATH: "/snapshots"
    ports:
      - "8080:80"
